### ISSUE TITLE
Support manual amendment of changelog entries

### ISSUE THREAD

**Issue by TLINDEN** [chelnak/gh-changelog#104]
Hi,

would it somehow be possible to edit a generated Changelog in a way that `gh-changelog` keeps those edits? That way I could e.g. switch to a pull request workflow and edit past entries which didn't follow this workflow so they also have some information.

Maybe these amendments could be added to the config, e.g.:
```
amendments:
  v1.0.0:
    added:
      - feature
      - enhancement
    changed:
      - backwards-incompatible
    fixed:
      - bug
      - bugfix
      - documentation
```

This would help me a lot. I could switch using the extension for legacy projects etc.
